# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  # Server Mount Config

  fileSystems."/home/amoeba/mnt/server" =
    { device = "//192.168.50.62/Projects";
      fsType = "cifs";
      options = ["rw,auto,username=amoeba-amin,pass=8VvsThwkRJNsBXGBCWgX,uid=1000,file_mode=0777,dir_mode=0777,noperm"];
    };


  # ext ssd-mount config
  fileSystems."/home/amoeba/mnt/ssd-ext" =
    { device = "/dev/disk/by-uuid/f847ffc9-61d8-4fbc-8799-6370db71ae3c";
      fsType = "ext4";
      options = ["rw,auto"];
    };




  fileSystems."/" =
    { device = "/dev/disk/by-uuid/54895910-960f-44c6-86f2-fd7668ee63ea";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6D83-7CFA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b59f025f-0993-4ab1-aba2-559bf8f97737"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp67s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp67s0f1.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp68s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp69s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp70s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
